- name: Maintenance | showJobs
  ansible.builtin.shell: |
    set -eu
    {{ docker_compose }} exec wiki php maintenance/showJobs.php \
      || true
  args:
    chdir: "{{ WIKI_INSTALLATION_PATH }}"
  environment: "{{ proxy_env }}"
